### ISSUE TITLE
How to install opensearch-dashboards-plugin and watcher in opensearch kubernates cluster

### ISSUE THREAD

**Issue by ganilmca** [opensearch-project/dashboards-reporting#361] opened 2024-06-06 08:53 UTC
Hi Team,

Can any one help me to install OpenSearch Dashboards Monitoring Plugin and watcher plugin to monitor and send notifications when cluster is not green state.

Am not able to download those plugins, the below link also not working.
https://artifacts.opensearch.org/releases/plugins

Please tell us wher to download those plugins.

Is opensearch support to watcher and cluster monitor?

If so, please provide download links for plugins.

Thanks
Anil.

**Comment by dblock** [comment] 2024-07-01 16:16
It's probably best to ask this question in forums or public Slack first. Closing this issue here for now, but please feel free to reopen if this is caused by a bug.

[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]

**Closed by dblock** 2024-07-01 16:16 UTC
Labels: enhancement, untriaged
